/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LatexSuiteExtension
});
module.exports = __toCommonJS(main_exports);
var import_view4 = require("@codemirror/view");
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian2 = require("obsidian");

// src/rtl.ts
var import_obsidian = require("obsidian");
var DEFAULT_RTL_TEXT_COMMANDS = ["he", "ar"];
var DEFAULT_HEBREW_FONT = "David CLM";
var DEFAULT_ARABIC_FONT = "";
var ARABIC_RE = /[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]/;
function mergeSplitRtlText(root) {
  const handled = /* @__PURE__ */ new Set();
  for (const el of Array.from(root.querySelectorAll("mjx-utext"))) {
    if (handled.has(el))
      continue;
    const run = [el];
    let next = el.nextElementSibling;
    while (next && next.tagName === el.tagName) {
      run.push(next);
      handled.add(next);
      next = next.nextElementSibling;
    }
    if (run.length < 2)
      continue;
    const text = run.map((e) => {
      var _a;
      return (_a = e.textContent) != null ? _a : "";
    }).join("");
    if (!ARABIC_RE.test(text))
      continue;
    el.textContent = text;
    el.style.removeProperty("width");
    for (const extra of run.slice(1))
      extra.remove();
  }
}
function buildRtlFontStack(hebrewFont, arabicFont) {
  return [hebrewFont, arabicFont].map((font) => font.trim().replace(/["\\]/g, "")).filter(Boolean).map((font) => `"${font}"`).join(", ");
}
var MathJaxBidiCommandPatcher = class {
  constructor(cmds) {
    this.cmds = cmds;
  }
  async init() {
    await (0, import_obsidian.loadMathJax)();
    mergeSplitRtlText(document.body);
    this.arabicShapingObserver = new MutationObserver((mutations) => {
      var _a;
      for (const mutation of mutations) {
        for (const node of Array.from(mutation.addedNodes)) {
          if (!node.instanceOf(HTMLElement))
            continue;
          if (node.tagName.startsWith("MJX")) {
            mergeSplitRtlText((_a = node.parentElement) != null ? _a : node);
          } else if (node.querySelector("mjx-utext")) {
            mergeSplitRtlText(node);
          }
        }
      }
    });
    this.arabicShapingObserver.observe(document.body, { childList: true, subtree: true });
    const defs = this.cmds.map((cmd) => cmd.trim().replace(/^\\/, "")).filter((cmd) => /^[A-Za-z]+$/.test(cmd)).map((cmd) => `\\def\\${cmd}#1{\\class{mjx-rtl}{\\text{#1}}}`);
    if (defs.length === 0)
      return;
    window.MathJax.tex2chtml(defs.join("\n"), { display: false });
    await (0, import_obsidian.finishRenderMath)();
    this.patchStyles();
    const mathjaxStyleEl = this.getMathJaxStyleElement();
    if (mathjaxStyleEl) {
      this.mathjaxStyleObserver = new MutationObserver(() => this.patchStyles());
      this.mathjaxStyleObserver.observe(mathjaxStyleEl, {
        attributes: true
      });
    }
  }
  destroy() {
    var _a, _b;
    (_a = this.mathjaxStyleObserver) == null ? void 0 : _a.disconnect();
    this.mathjaxStyleObserver = void 0;
    (_b = this.arabicShapingObserver) == null ? void 0 : _b.disconnect();
    this.arabicShapingObserver = void 0;
    if (this.logicalSheet) {
      document.adoptedStyleSheets = document.adoptedStyleSheets.filter(
        (sheet) => sheet !== this.logicalSheet
      );
      this.logicalSheet = void 0;
    }
  }
  /**
   * The mirrored rules depend on MathJax's generated stylesheet, so they
   * can't live in styles.css; a constructed stylesheet (no <style> element)
   * carries them instead.
   */
  patchStyles() {
    const rules = this.convertMathJaxStylesToLogicalProperties();
    if (!this.logicalSheet) {
      this.logicalSheet = new CSSStyleSheet();
      document.adoptedStyleSheets = [...document.adoptedStyleSheets, this.logicalSheet];
    }
    this.logicalSheet.replaceSync(rules.join("\n"));
  }
  getMathJaxStyleElement() {
    return document.getElementById("MJX-CHTML-styles");
  }
  convertMathJaxStylesToLogicalProperties() {
    const rules = [];
    const styleEl = this.getMathJaxStyleElement();
    if (!styleEl || !styleEl.sheet)
      return rules;
    for (const rule of Array.from(styleEl.sheet.cssRules)) {
      if (!(rule instanceof CSSStyleRule))
        continue;
      const styleLines = [];
      const paddingLeft = rule.style.getPropertyValue("padding-left");
      const paddingRight = rule.style.getPropertyValue("padding-right");
      const marginLeft = rule.style.getPropertyValue("margin-left");
      const marginRight = rule.style.getPropertyValue("margin-right");
      if (paddingLeft)
        styleLines.push(`padding-inline-start: ${paddingLeft};`);
      if (paddingRight)
        styleLines.push(`padding-inline-end: ${paddingRight};`);
      if (marginLeft)
        styleLines.push(`margin-inline-start: ${marginLeft};`);
      if (marginRight)
        styleLines.push(`margin-inline-end: ${marginRight};`);
      if (styleLines.length > 0) {
        const newRule = `${rule.selectorText} {
  ${styleLines.join("\n  ")}
}`;
        rules.push(newRule);
      }
    }
    return rules;
  }
};

// src/solve-core.ts
var SEPARATOR_COMMANDS = /* @__PURE__ */ new Set([
  "quad",
  "qquad",
  "implies",
  "impliedby",
  "iff",
  "Rightarrow",
  "Leftarrow",
  "Leftrightarrow",
  "Longrightarrow",
  "Longleftarrow",
  "rightarrow",
  "leftarrow",
  "leftrightarrow",
  "longrightarrow",
  "to",
  "mapsto",
  "xrightarrow",
  "xleftarrow"
]);
var FUNCTIONS = {
  sin: Math.sin,
  cos: Math.cos,
  tan: Math.tan,
  arcsin: Math.asin,
  arccos: Math.acos,
  arctan: Math.atan,
  sinh: Math.sinh,
  cosh: Math.cosh,
  tanh: Math.tanh,
  ln: Math.log,
  log: Math.log10,
  exp: Math.exp
};
var DEFAULT_ANGLE_NAMES = [
  "theta",
  "vartheta",
  "phi",
  "varphi",
  "alpha",
  "beta",
  "gamma",
  "delta",
  "psi"
];
function escapeRegex(text) {
  return text.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function isAngleName(lhs, angleNames) {
  const s = lhs.trim();
  for (const raw of angleNames) {
    const name = raw.trim().replace(/^\\/, "");
    if (!name)
      continue;
    if (new RegExp(`^\\\\?${escapeRegex(name)}(?![A-Za-z])`).test(s))
      return true;
  }
  return false;
}
var INVERSE_FUNCTIONS = {
  sin: Math.asin,
  cos: Math.acos,
  tan: Math.atan,
  arcsin: Math.sin,
  arccos: Math.cos,
  arctan: Math.tan,
  sinh: Math.asinh,
  cosh: Math.acosh,
  tanh: Math.atanh,
  ln: Math.exp,
  exp: Math.log,
  log: (x) => Math.pow(10, x)
};
function tokenize(latex) {
  const src = latex.replace(/\\left\b|\\right\b/g, " ").replace(/\\[,:;!]|\\ /g, " ").replace(/~/g, " ").replace(/\\cdot\b|\\times\b/g, "*").replace(/\\div\b/g, "/").replace(/\\[cdt]frac\b/g, "\\frac").replace(/[×·⋅∙]/g, "*").replace(/[−–]/g, "-").replace(/÷/g, "/").replace(/π/g, "\\pi ");
  const toks = [];
  let i = 0;
  while (i < src.length) {
    const c = src[i];
    if (/\s/.test(c)) {
      i++;
      continue;
    }
    if (/[0-9.]/.test(c)) {
      let j = i;
      while (j < src.length && /[0-9.]/.test(src[j]))
        j++;
      const num = parseFloat(src.slice(i, j));
      if (isNaN(num))
        return null;
      toks.push({ t: "num", v: num });
      i = j;
      continue;
    }
    if (c === "\\") {
      let j = i + 1;
      while (j < src.length && /[a-zA-Z]/.test(src[j]))
        j++;
      if (j === i + 1)
        return null;
      toks.push({ t: "cmd", v: src.slice(i + 1, j) });
      i = j;
      continue;
    }
    if (/[a-zA-Z]/.test(c) || "{}()[]^+-*/_".includes(c)) {
      toks.push({ t: "ch", v: c });
      i++;
      continue;
    }
    return null;
  }
  return toks;
}
function evaluateLatexResult(latex) {
  const toks = tokenize(latex);
  if (!toks || toks.length === 0)
    return null;
  let p = 0;
  let angleResult = null;
  const fail = () => {
    throw new Error("unparseable");
  };
  const peek = () => toks[p];
  const expectCh = (ch) => {
    const t = peek();
    if (!t || t.t !== "ch" || t.v !== ch)
      fail();
    p++;
  };
  const parseExpr = () => {
    let v = parseTerm();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && (t.v === "+" || t.v === "-")) {
        p++;
        const rhs = parseTerm();
        v = t.v === "+" ? v + rhs : v - rhs;
      } else
        break;
    }
    return v;
  };
  const startsFactor = (t) => {
    if (!t)
      return false;
    if (t.t === "num")
      return true;
    if (t.t === "cmd")
      return t.v === "frac" || t.v === "sqrt" || t.v === "pi" || t.v in FUNCTIONS;
    return t.v === "(" || t.v === "{" || /[a-zA-Z]/.test(t.v);
  };
  const parseTerm = () => {
    let v = parseUnary();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && (t.v === "*" || t.v === "/")) {
        p++;
        const rhs = parseUnary();
        v = t.v === "*" ? v * rhs : v / rhs;
      } else if (startsFactor(t)) {
        v = v * parseUnary();
      } else
        break;
    }
    return v;
  };
  const parseUnary = () => {
    const t = peek();
    if (t && t.t === "ch" && (t.v === "-" || t.v === "+")) {
      p++;
      const v = parseUnary();
      return t.v === "-" ? -v : v;
    }
    return parsePow();
  };
  const parsePow = () => {
    let base = parseAtom();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && t.v === "^") {
        p++;
        const et = peek();
        if (et && et.t === "cmd" && et.v === "circ") {
          p++;
          base = base * (Math.PI / 180);
          continue;
        }
        const t1 = toks[p + 1];
        const t2 = toks[p + 2];
        if (et && et.t === "ch" && et.v === "{" && t1 && t1.t === "cmd" && t1.v === "circ" && t2 && t2.t === "ch" && t2.v === "}") {
          p += 3;
          base = base * (Math.PI / 180);
          continue;
        }
        const exp = et && et.t === "ch" && (et.v === "-" || et.v === "+") ? parseUnary() : parseAtom();
        base = Math.pow(base, exp);
      } else if (t && t.t === "ch" && t.v === "_") {
        fail();
      } else
        break;
    }
    return base;
  };
  const parseBraced = () => {
    expectCh("{");
    const v = parseExpr();
    expectCh("}");
    return v;
  };
  const parseAtom = () => {
    const t = peek();
    if (!t)
      fail();
    if (t.t === "num") {
      p++;
      return t.v;
    }
    if (t.t === "cmd") {
      p++;
      if (t.v === "pi")
        return Math.PI;
      if (t.v === "frac") {
        const a = parseBraced();
        const b = parseBraced();
        return a / b;
      }
      if (t.v === "sqrt") {
        let n = 2;
        const nt = peek();
        if (nt && nt.t === "ch" && nt.v === "[") {
          p++;
          n = parseExpr();
          expectCh("]");
        }
        return Math.pow(parseBraced(), 1 / n);
      }
      if (t.v in FUNCTIONS) {
        let power = null;
        const nt = peek();
        if (nt && nt.t === "ch" && nt.v === "^") {
          p++;
          const et = peek();
          power = et && et.t === "ch" && (et.v === "-" || et.v === "+") ? parseUnary() : parseAtom();
        }
        if (power === -1) {
          const inverse = INVERSE_FUNCTIONS[t.v];
          if (!inverse)
            fail();
          const inverted = inverse(parseUnary());
          if (t.v === "sin" || t.v === "cos" || t.v === "tan")
            angleResult = inverted;
          return inverted;
        }
        const value = FUNCTIONS[t.v](parseUnary());
        if (power === null) {
          if (t.v === "arcsin" || t.v === "arccos" || t.v === "arctan")
            angleResult = value;
          return value;
        }
        return Math.pow(value, power);
      }
      fail();
    }
    if (t.t === "ch") {
      if (t.v === "(") {
        p++;
        const v = parseExpr();
        expectCh(")");
        return v;
      }
      if (t.v === "{") {
        p++;
        const v = parseExpr();
        expectCh("}");
        return v;
      }
      if (t.v === "e") {
        p++;
        return Math.E;
      }
    }
    return fail();
  };
  try {
    const value = parseExpr();
    if (p !== toks.length)
      return null;
    if (!isFinite(value))
      return null;
    return { value, isAngle: angleResult !== null && value === angleResult };
  } catch (e) {
    return null;
  }
}
var KNOWN_COMMANDS = /* @__PURE__ */ new Set(["frac", "sqrt", "pi", "circ", ...Object.keys(FUNCTIONS)]);
var polyTrim = (a) => {
  const r = [...a];
  while (r.length > 1 && r[r.length - 1] === 0)
    r.pop();
  return r;
};
var polyIsConst = (a) => polyTrim(a).length === 1;
var polyConst = (a) => polyTrim(a)[0];
var polyAdd = (a, b) => {
  var _a, _b;
  const r = [];
  for (let i = 0; i < Math.max(a.length, b.length); i++)
    r.push(((_a = a[i]) != null ? _a : 0) + ((_b = b[i]) != null ? _b : 0));
  return r;
};
var polyNeg = (a) => a.map((c) => -c);
var polySub = (a, b) => polyAdd(a, polyNeg(b));
var polyMul = (a, b) => {
  const r = new Array(a.length + b.length - 1).fill(0);
  for (let i = 0; i < a.length; i++) {
    for (let j = 0; j < b.length; j++)
      r[i + j] += a[i] * b[j];
  }
  return r;
};
function evaluatePolynomial(latex) {
  const toks = tokenize(latex);
  if (!toks || toks.length === 0)
    return null;
  const candidates = /* @__PURE__ */ new Set();
  for (const t of toks) {
    if (t.t === "ch" && /[A-Za-z]/.test(t.v) && t.v !== "e")
      candidates.add(t.v);
    else if (t.t === "cmd" && !KNOWN_COMMANDS.has(t.v))
      candidates.add("\\" + t.v);
  }
  if (candidates.size > 1)
    return null;
  const variable = candidates.size === 1 ? [...candidates][0] : null;
  let p = 0;
  const fail = () => {
    throw new Error("unparseable");
  };
  const peek = () => toks[p];
  const expectCh = (ch) => {
    const t = peek();
    if (!t || t.t !== "ch" || t.v !== ch)
      fail();
    p++;
  };
  const parseExpr = () => {
    let v = parseTerm();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && (t.v === "+" || t.v === "-")) {
        p++;
        const rhs = parseTerm();
        v = t.v === "+" ? polyAdd(v, rhs) : polySub(v, rhs);
      } else
        break;
    }
    return v;
  };
  const startsFactor = (t) => {
    if (!t)
      return false;
    if (t.t === "num")
      return true;
    if (t.t === "cmd")
      return true;
    return t.v === "(" || t.v === "{" || /[A-Za-z]/.test(t.v);
  };
  const parseTerm = () => {
    let v = parseUnary();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && (t.v === "*" || t.v === "/")) {
        p++;
        const rhs = parseUnary();
        if (t.v === "*") {
          v = polyMul(v, rhs);
        } else {
          if (!polyIsConst(rhs) || polyConst(rhs) === 0)
            fail();
          v = v.map((c) => c / polyConst(rhs));
        }
      } else if (startsFactor(t)) {
        v = polyMul(v, parseUnary());
      } else
        break;
    }
    return v;
  };
  const parseUnary = () => {
    const t = peek();
    if (t && t.t === "ch" && (t.v === "-" || t.v === "+")) {
      p++;
      const v = parseUnary();
      return t.v === "-" ? polyNeg(v) : v;
    }
    return parsePow();
  };
  const parsePow = () => {
    let base = parseAtom();
    for (; ; ) {
      const t = peek();
      if (t && t.t === "ch" && t.v === "^") {
        p++;
        const et = peek();
        if (et && et.t === "cmd" && et.v === "circ") {
          p++;
          if (!polyIsConst(base))
            fail();
          base = [polyConst(base) * (Math.PI / 180)];
          continue;
        }
        const t1 = toks[p + 1];
        const t2 = toks[p + 2];
        if (et && et.t === "ch" && et.v === "{" && t1 && t1.t === "cmd" && t1.v === "circ" && t2 && t2.t === "ch" && t2.v === "}") {
          p += 3;
          if (!polyIsConst(base))
            fail();
          base = [polyConst(base) * (Math.PI / 180)];
          continue;
        }
        const exp = et && et.t === "ch" && (et.v === "-" || et.v === "+") ? parseUnary() : parseAtom();
        if (!polyIsConst(exp))
          fail();
        const e = polyConst(exp);
        if (polyIsConst(base)) {
          base = [Math.pow(polyConst(base), e)];
        } else {
          if (!Number.isInteger(e) || e < 0 || e > 6)
            fail();
          let r = [1];
          for (let k = 0; k < e; k++)
            r = polyMul(r, base);
          base = r;
        }
      } else if (t && t.t === "ch" && t.v === "_") {
        fail();
      } else
        break;
    }
    return base;
  };
  const parseBraced = () => {
    expectCh("{");
    const v = parseExpr();
    expectCh("}");
    return v;
  };
  const parseAtom = () => {
    const t = peek();
    if (!t)
      fail();
    if (t.t === "num") {
      p++;
      return [t.v];
    }
    if (t.t === "cmd") {
      p++;
      if ("\\" + t.v === variable)
        return [0, 1];
      if (t.v === "pi")
        return [Math.PI];
      if (t.v === "frac") {
        const a = parseBraced();
        const b = parseBraced();
        if (!polyIsConst(b) || polyConst(b) === 0)
          fail();
        return a.map((c) => c / polyConst(b));
      }
      if (t.v === "sqrt") {
        let n = 2;
        const nt = peek();
        if (nt && nt.t === "ch" && nt.v === "[") {
          p++;
          const nPoly = parseExpr();
          expectCh("]");
          if (!polyIsConst(nPoly))
            fail();
          n = polyConst(nPoly);
        }
        const arg = parseBraced();
        if (!polyIsConst(arg))
          fail();
        return [Math.pow(polyConst(arg), 1 / n)];
      }
      if (t.v in FUNCTIONS) {
        const arg = parseUnary();
        if (!polyIsConst(arg))
          fail();
        return [FUNCTIONS[t.v](polyConst(arg))];
      }
      return fail();
    }
    if (t.t === "ch") {
      if (t.v === "(") {
        p++;
        const v = parseExpr();
        expectCh(")");
        return v;
      }
      if (t.v === "{") {
        p++;
        const v = parseExpr();
        expectCh("}");
        return v;
      }
      if (t.v === variable) {
        p++;
        return [0, 1];
      }
      if (t.v === "e") {
        p++;
        return [Math.E];
      }
    }
    return fail();
  };
  try {
    const poly = polyTrim(parseExpr());
    if (p !== toks.length)
      return null;
    if (!poly.every(isFinite))
      return null;
    return { poly, variable };
  } catch (e) {
    return null;
  }
}
function tryPolynomialSolve(lhs, rhs, separator) {
  var _a;
  const right = evaluatePolynomial(rhs);
  if (!right)
    return null;
  let combined;
  let variable;
  if (lhs) {
    const left = evaluatePolynomial(lhs);
    if (!left)
      return null;
    if (left.variable && right.variable && left.variable !== right.variable)
      return null;
    variable = (_a = left.variable) != null ? _a : right.variable;
    const bareUnknown = left.poly.length === 2 && left.poly[0] === 0 && left.poly[1] === 1;
    if (left.variable && bareUnknown && !right.variable)
      return null;
    combined = polySub(left.poly, right.poly);
  } else {
    variable = right.variable;
    combined = right.poly;
  }
  if (!variable)
    return null;
  combined = polyTrim(combined);
  const sep = separator.trim();
  const prefix = ` ${sep ? sep + " " : ""}`;
  if (combined.length === 3) {
    const [c, b, a] = combined;
    const discriminant = b * b - 4 * a * c;
    const tolerance = 1e-12 * Math.max(Math.abs(b * b), Math.abs(4 * a * c), 1);
    if (Math.abs(discriminant) <= tolerance) {
      return `${prefix}${variable}_{1,2}=${formatValue(-b / (2 * a))}`;
    }
    if (discriminant > 0) {
      const r1 = (-b + Math.sqrt(discriminant)) / (2 * a);
      const r2 = (-b - Math.sqrt(discriminant)) / (2 * a);
      return `${prefix}${variable}_1=${formatValue(r1)},\\ ${variable}_2=${formatValue(r2)}`;
    }
    const re = -b / (2 * a);
    const im = Math.abs(Math.sqrt(-discriminant) / (2 * a));
    const reStr = formatValue(re) === "0" ? "" : formatValue(re);
    const imStr = formatValue(im) === "1" ? "i" : `${formatValue(im)}i`;
    return `${prefix}${variable}_{1,2}=${reStr}\\pm ${imStr}`;
  }
  if (combined.length === 2) {
    return `${prefix}${variable}=${formatValue(-combined[0] / combined[1])}`;
  }
  return null;
}
function skipGroups(s, i) {
  for (; ; ) {
    let j = i;
    while (j < s.length && /\s/.test(s[j]))
      j++;
    const open = s[j];
    if (open !== "{" && open !== "[")
      return i;
    const close = open === "{" ? "}" : "]";
    let depth = 0;
    while (j < s.length) {
      if (s[j] === "\\") {
        j += 2;
        continue;
      }
      if (s[j] === open)
        depth++;
      else if (s[j] === close) {
        depth--;
        if (depth === 0) {
          j++;
          break;
        }
      }
      j++;
    }
    i = j;
  }
}
function splitTopLevelSegments(content) {
  const segments = [];
  let depth = 0;
  let start = 0;
  let i = 0;
  while (i < content.length) {
    const c = content[i];
    if (c === "\\") {
      let j = i + 1;
      while (j < content.length && /[a-zA-Z]/.test(content[j]))
        j++;
      const name = content.slice(i + 1, j);
      if (depth === 0 && SEPARATOR_COMMANDS.has(name)) {
        segments.push(content.slice(start, i));
        start = i = skipGroups(content, j);
        continue;
      }
      i = name ? j : i + 2;
      continue;
    }
    if (c === "{" || c === "(" || c === "[")
      depth++;
    else if (c === "}" || c === ")" || c === "]")
      depth = Math.max(0, depth - 1);
    else if (depth === 0 && (c === "," || c === ";" || c === ":")) {
      segments.push(content.slice(start, i));
      start = i + 1;
    }
    i++;
  }
  segments.push(content.slice(start));
  return segments;
}
var LABEL_COMMAND = /^\\(?:he|ar|text|textrm|textbf|textit|mathrm|mbox)\s*(?=\{)/;
var LABEL_SPACING = /^(?:\\[,;:!]|\\ |\\quad\b|\\qquad\b|:)\s*/;
function stripLeadingLabels(text) {
  let s = text.trim();
  for (; ; ) {
    const cmd = s.match(LABEL_COMMAND);
    if (cmd) {
      const afterGroup = skipGroups(s, cmd[0].length);
      if (afterGroup > cmd[0].length) {
        s = s.slice(afterGroup).trim();
        continue;
      }
    }
    const spacing = s.match(LABEL_SPACING);
    if (spacing && spacing[0].length > 0) {
      s = s.slice(spacing[0].length).trim();
      continue;
    }
    break;
  }
  return s;
}
function findTopLevelEquals(segment) {
  const positions = [];
  let depth = 0;
  let i = 0;
  while (i < segment.length) {
    const c = segment[i];
    if (c === "\\") {
      let j = i + 1;
      while (j < segment.length && /[a-zA-Z]/.test(segment[j]))
        j++;
      const name = segment.slice(i + 1, j);
      if (depth === 0 && (name === "approx" || name === "simeq")) {
        positions.push({ index: i, length: j - i });
      }
      i = j === i + 1 ? i + 2 : j;
      continue;
    }
    if (c === "{" || c === "(" || c === "[")
      depth++;
    else if (c === "}" || c === ")" || c === "]")
      depth = Math.max(0, depth - 1);
    else if (depth === 0 && c === "=")
      positions.push({ index: i, length: 1 });
    i++;
  }
  return positions;
}
function formatValue(v) {
  if (v === 0)
    return "0";
  const rounded = Math.round(v);
  if (rounded !== 0 && Math.abs(v - rounded) <= 1e-9 * Math.abs(rounded))
    return String(rounded);
  const s = v.toPrecision(6);
  if (!s.includes("e")) {
    return s.includes(".") ? s.replace(/0+$/, "").replace(/\.$/, "") : s;
  }
  const [mantissa, exponent] = s.split("e");
  const m = mantissa.replace(/0+$/, "").replace(/\.$/, "");
  return `${m}\\cdot 10^{${parseInt(exponent, 10)}}`;
}
function computeSolveInsertion(mathContent, separator, angleUnit = "degrees", angleNames = DEFAULT_ANGLE_NAMES) {
  const content = mathContent.replace(/\\displaystyle\b/g, " ");
  const segments = splitTopLevelSegments(content).map((s) => s.trim()).filter(Boolean);
  if (segments.length === 0)
    return null;
  let lhs = "";
  let rhs = "";
  for (let i = segments.length - 1; i >= 0; i--) {
    const equals = findTopLevelEquals(segments[i]);
    if (equals.length > 0) {
      const last = equals[equals.length - 1];
      lhs = stripLeadingLabels(segments[i].slice(0, equals[0].index));
      rhs = segments[i].slice(last.index + last.length).trim();
      break;
    }
  }
  if (!rhs) {
    rhs = segments[segments.length - 1];
  }
  const polySolution = tryPolynomialSolve(lhs, rhs, separator);
  if (polySolution !== null)
    return polySolution;
  let unit = "";
  const unitMatch = rhs.match(/^([\s\S]*?)(?:\\ |\s)*\\(mathrm|text)\{([^{}]*)\}\s*$/);
  if (unitMatch) {
    rhs = unitMatch[1].trim();
    unit = `\\ \\${unitMatch[2]}{${unitMatch[3]}}`;
  }
  if (!rhs)
    return null;
  const NAME_RE = /^\\?[A-Za-z]+(?:_(?:\{[\s\S]*\}|[A-Za-z0-9]))?$/;
  if (lhs && !NAME_RE.test(lhs.trim()) && evaluateLatexResult(lhs) === null)
    return null;
  const result = evaluateLatexResult(rhs);
  if (result === null)
    return null;
  const isAngle = result.isAngle && (lhs === "" || isAngleName(lhs, angleNames));
  const formatted = isAngle && angleUnit === "degrees" ? formatValue(result.value * 180 / Math.PI) + "^\\circ" : formatValue(result.value);
  if (lhs) {
    const sep = separator.trim();
    return ` ${sep ? sep + " " : ""}${lhs}=${formatted}${unit}`;
  }
  return `=${formatted}${unit}`;
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  disableInTable: false,
  disableOnIME: true,
  inlineDisplaystyle: true,
  autoPairDollar: true,
  solveSeparator: "\\quad \\to \\quad",
  solveAngleUnit: "degrees",
  solveAngleNames: DEFAULT_ANGLE_NAMES,
  builtinSnippets: true,
  rtlTextCommands: DEFAULT_RTL_TEXT_COMMANDS,
  hebrewFont: DEFAULT_HEBREW_FONT,
  arabicFont: DEFAULT_ARABIC_FONT,
  autoSwitchKeyboard: true,
  imSelectPath: "",
  hebrewInputSource: "com.apple.keylayout.Hebrew",
  arabicInputSource: "com.apple.keylayout.Arabic",
  mathInputSource: "com.apple.keylayout.ABC",
  noteInputSource: "com.apple.keylayout.Hebrew",
  disableDecorations: false,
  disableAtomicRanges: false
};
var LatexSuiteExtensionSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    /** re-registering MathJax macros is not free; don't do it per keystroke */
    this.refreshMathJaxSoon = (0, import_obsidian2.debounce)(() => {
      void this.plugin.refreshMathJax();
    }, 1e3, true);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        type: "group",
        heading: "Flicker-free inline math",
        items: [
          {
            name: "Disable in tables",
            desc: "If turned on, braces won't be inserted in tables. Decorations & atomic ranges are enabled regardless of this setting.",
            control: { type: "toggle", key: "disableInTable" }
          },
          {
            name: "Disable when using IME input",
            desc: "This option can be helpful for avoiding some strange behavior occurring when using IME inputs after escaping from a math block with the Latex Suite plugin's tabout feature.",
            control: { type: "toggle", key: "disableOnIME" }
          }
        ]
      },
      {
        type: "group",
        heading: "Math rendering",
        items: [
          {
            name: "Display style for inline math",
            desc: createFragment((el) => {
              el.createSpan({ text: 'Render every inline math as if it started with "' });
              el.createEl("code", { text: "\\displaystyle" });
              el.createSpan({ text: '" \u2014 full-size fractions, sums and integrals inside $...$. Re-open notes to re-render already displayed math.' });
            }),
            control: { type: "toggle", key: "inlineDisplaystyle" }
          },
          {
            name: "Auto-close $",
            desc: createFragment((el) => {
              el.createSpan({ text: 'Typing "' });
              el.createEl("code", { text: "$" });
              el.createSpan({ text: '" inserts "' });
              el.createEl("code", { text: "$|$" });
              el.createSpan({ text: '" with the cursor in the middle. Typing "$" before a closing "$" steps over it, and typing "$" with a selection wraps it in $...$.' });
            }),
            control: { type: "toggle", key: "autoPairDollar" }
          },
          {
            name: "Built-in snippets",
            desc: createFragment((el) => {
              el.createSpan({ text: 'In math, "' });
              el.createEl("code", { text: "he" });
              el.createSpan({ text: '" expands to \\he{}, "' });
              el.createEl("code", { text: "ar" });
              el.createSpan({ text: '" to \\ar{}, and "' });
              el.createEl("code", { text: "sol" });
              el.createSpan({ text: '" to \\solve \u2014 no Latex Suite configuration needed. Never fires after a letter or backslash (\\theta is safe), inside \\text{...}, or inside \\he{...}/\\ar{...}.' });
            }),
            control: { type: "toggle", key: "builtinSnippets" }
          }
        ]
      },
      {
        type: "group",
        heading: "Solve",
        items: [
          {
            name: "Result separator",
            desc: createFragment((el) => {
              el.createSpan({ text: 'Typing "' });
              el.createEl("code", { text: "\\solve" });
              el.createSpan({ text: '" after an equation like "' });
              el.createEl("code", { text: "k_1=\\frac{200}{40}" });
              el.createSpan({ text: '" evaluates the last expression and inserts the result ("' });
              el.createEl("code", { text: "k_1=5" });
              el.createSpan({ text: '"). This text is inserted between the equation and the result.' });
            }),
            control: { type: "text", key: "solveSeparator", placeholder: "\\quad \\to \\quad" }
          },
          {
            name: "Angle results",
            desc: createFragment((el) => {
              el.createSpan({ text: 'When the result is an angle \u2014 inverse trig like "' });
              el.createEl("code", { text: "\\sin^{-1}(0.5)" });
              el.createSpan({ text: '" assigned to an angle-named variable \u2014 show it in degrees with "' });
              el.createEl("code", { text: "^\\circ" });
              el.createSpan({ text: '" or as plain radians.' });
            }),
            control: {
              type: "dropdown",
              key: "solveAngleUnit",
              options: { degrees: "Degrees", radians: "Radians" }
            }
          },
          {
            name: "Angle variable names",
            desc: createFragment((el) => {
              el.createSpan({ text: 'Comma-separated variable names that count as angles. "' });
              el.createEl("code", { text: "\\theta_{c}=\\sin^{-1}(...)" });
              el.createSpan({ text: '" gets degrees; "' });
              el.createEl("code", { text: "r_{c}=\\sin^{-1}(...)" });
              el.createSpan({ text: '" stays a plain number.' });
            }),
            control: { type: "text", key: "solveAngleNames", placeholder: DEFAULT_ANGLE_NAMES.join(", ") }
          }
        ]
      },
      {
        type: "group",
        heading: "RTL math text",
        items: [
          {
            name: "RTL text commands",
            desc: createFragment((el) => {
              el.createSpan({ text: 'Each command wraps its argument as RTL text inside math \u2014 the \\text{} is built in, so \\he{...} is all you type. Comma-separated list; with the default "he, ar", writing "' });
              el.createEl("code", { text: "\\he{\u05E9\u05DC\u05D5\u05DD}" });
              el.createSpan({ text: '" renders Hebrew text; nest math inside via "' });
              el.createEl("code", { text: "\\(...\\)" });
              el.createSpan({ text: '". Changes may require restarting Obsidian to take full effect.' });
            }),
            control: { type: "text", key: "rtlTextCommands", placeholder: "e.g. he, ar" }
          },
          {
            name: "Hebrew font",
            desc: "Font used for Hebrew text inside math. The font must be installed on your system (or provided by an Obsidian theme/snippet).",
            control: { type: "text", key: "hebrewFont", placeholder: DEFAULT_HEBREW_FONT }
          },
          {
            name: "Arabic font",
            desc: "Font used for Arabic text inside math. Leave empty to use the default math text font.",
            control: { type: "text", key: "arabicFont", placeholder: "e.g. Amiri" }
          }
        ]
      },
      {
        type: "group",
        heading: "Keyboard switching",
        visible: () => import_obsidian2.Platform.isDesktopApp,
        items: [
          {
            name: "Auto-switch keyboard input",
            desc: 'Switch the system keyboard by cursor position: the note language outside math, the math language inside $...$, and Hebrew/Arabic inside \\he{...} / \\ar{...}. Requires the im-select command-line tool. Tip: bind the "Toggle keyboard auto-switching" command to a hotkey to pause this quickly.',
            control: { type: "toggle", key: "autoSwitchKeyboard" }
          },
          {
            name: "im-select path",
            desc: "Leave empty to auto-detect (/opt/homebrew/bin/im-select or /usr/local/bin/im-select).",
            control: { type: "text", key: "imSelectPath", placeholder: "auto-detect" }
          },
          {
            name: "Hebrew input source",
            desc: "Keyboard layout ID used inside \\he{...}. Run im-select in a terminal with the layout active to print its ID.",
            control: { type: "text", key: "hebrewInputSource", placeholder: "com.apple.keylayout.Hebrew" }
          },
          {
            name: "Arabic input source",
            desc: "Keyboard layout ID used inside \\ar{...}.",
            control: { type: "text", key: "arabicInputSource", placeholder: "com.apple.keylayout.Arabic" }
          },
          {
            name: "Math input source",
            desc: "Keyboard layout ID used inside $...$ (outside \\he / \\ar). Leave empty to not switch when entering math.",
            control: { type: "text", key: "mathInputSource", placeholder: "com.apple.keylayout.ABC" }
          },
          {
            name: "Note input source",
            desc: "Keyboard layout ID for regular note text, applied when leaving math \u2014 the main language of your notes. Leave empty to not switch outside math.",
            control: { type: "text", key: "noteInputSource", placeholder: "com.apple.keylayout.Hebrew" }
          }
        ]
      },
      {
        type: "group",
        heading: "Debug mode",
        items: [
          {
            name: "Disable decorations",
            desc: "If turned on, decorations to hide braces adjacent to dollar signs are disabled. This is especially useful when you want to see what this plugin does under the hood.",
            control: { type: "toggle", key: "disableDecorations" }
          },
          {
            name: "Disable atomic ranges",
            desc: createFragment((el) => {
              el.createSpan({ text: 'If turned on, atomic ranges to treat each of "' });
              el.createEl("code", { text: "${} " });
              el.createSpan({ text: '" or "' });
              el.createEl("code", { text: " {}$" });
              el.createSpan({ text: '" as one character are disabled.' });
            }),
            control: { type: "toggle", key: "disableAtomicRanges" }
          },
          {
            name: "Restore defaults",
            desc: "Reset every setting of this plugin to its default value.",
            action: () => {
              void this.restoreDefaults();
            }
          }
        ]
      }
    ];
  }
  getControlValue(key) {
    if (key === "rtlTextCommands" || key === "solveAngleNames") {
      return this.plugin.settings[key].join(", ");
    }
    return this.plugin.settings[key];
  }
  async setControlValue(key, value) {
    const settings = this.plugin.settings;
    if (key === "rtlTextCommands" || key === "solveAngleNames") {
      if (typeof value !== "string")
        return;
      settings[key] = value.split(",").map((s) => s.trim()).filter(Boolean);
    } else if (typeof value === "string") {
      settings[key] = key === "solveSeparator" ? value : value.trim();
    } else if (typeof value === "boolean") {
      settings[key] = value;
    } else {
      return;
    }
    await this.plugin.saveSettings();
    switch (key) {
      case "disableDecorations":
      case "disableAtomicRanges":
        this.plugin.remakeViewPlugin();
        break;
      case "rtlTextCommands":
        this.refreshMathJaxSoon();
        break;
      case "hebrewFont":
      case "arabicFont":
        this.plugin.applyRtlFonts();
        break;
    }
  }
  async restoreDefaults() {
    this.plugin.settings = structuredClone(DEFAULT_SETTINGS);
    await this.plugin.saveSettings();
    this.plugin.remakeViewPlugin();
    await this.plugin.refreshMathJax();
    this.plugin.applyRtlFonts();
    this.update();
  }
};

// src/decoration-and-atomic-range.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_language2 = require("@codemirror/language");

// src/utils.ts
var import_language = require("@codemirror/language");
var INLINE_MATH_BEGIN = "formatting-math-begin";
var MATH_END = "formatting-math-end";
function nodeText(node, state) {
  return state.sliceDoc(node.from, node.to);
}
function isLoneDollar(node, state) {
  return nodeText(node, state) == "$" && state.sliceDoc(Math.max(0, node.from - 1), node.from) != "$" && state.sliceDoc(node.to, node.to + 1) != "$";
}
function isInlineMathBegin(node, state) {
  return node.name.includes(INLINE_MATH_BEGIN) && isLoneDollar(node, state);
}
function isInlineMathEnd(node, state) {
  return node.name.includes(MATH_END) && isLoneDollar(node, state);
}
function selectionSatisfies(state, predicate) {
  let ret = false;
  const tree = (0, import_language.syntaxTree)(state);
  for (const { from } of state.selection.ranges) {
    const line = state.doc.lineAt(from);
    tree.iterate({
      from: line.from,
      to: line.to,
      enter: (node) => {
        if (predicate(node)) {
          ret = true;
        }
      }
    });
  }
  return ret;
}

// src/decoration-and-atomic-range.ts
var DummyRangeValue = class extends import_state.RangeValue {
};
var createViewPlugin = (plugin) => import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.impl(view);
    }
    update(update) {
      this.impl(update.view);
    }
    impl(view) {
      const decorationBulder = new import_state.RangeSetBuilder();
      const atomicRangeBulder = new import_state.RangeSetBuilder();
      const tree = (0, import_language2.syntaxTree)(view.state);
      for (const { from, to } of view.visibleRanges) {
        tree.iterate({
          from,
          to,
          enter(node) {
            if (isInlineMathBegin(node, view.state)) {
              if (view.state.sliceDoc(node.to, node.to + 3) == "{} ") {
                decorationBulder.add(
                  node.to,
                  node.to + 3,
                  import_view.Decoration.replace({})
                );
                atomicRangeBulder.add(
                  node.from,
                  node.to + 3,
                  new DummyRangeValue()
                );
              }
            } else if (isInlineMathEnd(node, view.state)) {
              if (view.state.sliceDoc(node.from - 3, node.from) == " {}") {
                decorationBulder.add(
                  node.from - 3,
                  node.from,
                  import_view.Decoration.replace({})
                );
                atomicRangeBulder.add(
                  node.from - 3,
                  node.to,
                  new DummyRangeValue()
                );
              }
            }
          }
        });
      }
      this.decorations = decorationBulder.finish();
      this.atomicRanges = atomicRangeBulder.finish();
    }
  },
  {
    decorations: (instance) => plugin.settings.disableDecorations ? import_view.Decoration.none : instance.decorations,
    provide: (viewPlugin) => import_view.EditorView.atomicRanges.of((view) => {
      var _a, _b;
      return plugin.settings.disableAtomicRanges ? import_state.RangeSet.empty : (_b = (_a = view.plugin(viewPlugin)) == null ? void 0 : _a.atomicRanges) != null ? _b : import_state.RangeSet.empty;
    })
  }
);

// src/tolerant-math.ts
var import_obsidian3 = require("obsidian");
var import_state2 = require("@codemirror/state");
var import_view2 = require("@codemirror/view");
var import_language3 = require("@codemirror/language");
var CANDIDATE_REGEX = /(?<![$\\])\$(?!\$)([^$\n]*?)(?<!\\)\$(?!\$)/g;
var EXCLUDED_NODE = /math|code|comment|frontmatter|escape|tag|hashtag/i;
function getTolerantConversionChanges(state, selection) {
  const tree = (0, import_language3.syntaxTree)(state);
  const changes = [];
  const seen = /* @__PURE__ */ new Set();
  for (const range of selection.ranges) {
    const line = state.doc.lineAt(range.head);
    CANDIDATE_REGEX.lastIndex = 0;
    let match;
    while ((match = CANDIDATE_REGEX.exec(line.text)) !== null) {
      const start = line.from + match.index;
      const end = start + match[0].length;
      if (range.from > end || range.to < start)
        continue;
      if (seen.has(start))
        continue;
      if (!shouldTolerantRender(match[1]))
        continue;
      const nodeName = tree.cursorAt(start, 1).node.name;
      if (EXCLUDED_NODE.test(nodeName) || /table/i.test(nodeName))
        continue;
      seen.add(start);
      changes.push({ from: start + 1, insert: "{} " });
      changes.push({ from: end - 1, insert: " {}" });
    }
  }
  return changes;
}
function shouldTolerantRender(content) {
  if (content.length === 0)
    return false;
  const trimmed = content.trim();
  if (trimmed.length === 0)
    return true;
  if (trimmed === content)
    return false;
  if (/^[ \t]/.test(content) && /[ \t]$/.test(content))
    return true;
  return !/[ \t]/.test(trimmed) || /[\\{}^_=+*/()[\]<>|]/.test(trimmed);
}
function renderTolerantMath(content) {
  const wrapper = createSpan({ cls: "lse-tolerant-math" });
  wrapper.append((0, import_obsidian3.renderMath)(content.trim(), false));
  return wrapper;
}
var MATH_BEGIN_MARK = import_view2.Decoration.mark({
  class: "cm-formatting cm-formatting-math cm-formatting-math-begin cm-math"
});
var MATH_END_MARK = import_view2.Decoration.mark({
  class: "cm-formatting cm-formatting-math cm-formatting-math-end cm-math"
});
var MATH_CONTENT_MARK = import_view2.Decoration.mark({ class: "cm-math" });
var TolerantMathWidget = class extends import_view2.WidgetType {
  constructor(content) {
    super();
    this.content = content;
  }
  eq(other) {
    return other.content === this.content;
  }
  toDOM() {
    const el = renderTolerantMath(this.content);
    void (0, import_obsidian3.finishRenderMath)();
    return el;
  }
  ignoreEvent() {
    return false;
  }
};
var tolerantMathViewPlugin = import_view2.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.conversionTimeout = -1;
      this.decorations = this.build(view);
    }
    update(update) {
      if (update.docChanged || update.selectionSet || update.viewportChanged) {
        this.decorations = this.build(update.view);
      }
    }
    destroy() {
      window.clearTimeout(this.conversionTimeout);
    }
    /**
     * Dispatching is not allowed during an update, so the conversion of a
     * touched candidate into the brace-guarded form runs on the next tick.
     * This catches every way a cursor can end up on a candidate — clicking,
     * arrow keys, typing the closing "$", or Latex Suite wrapping a
     * selection — the state is re-verified at fire time.
     */
    scheduleConversion(view) {
      if (this.conversionTimeout !== -1)
        return;
      this.conversionTimeout = window.setTimeout(() => {
        this.conversionTimeout = -1;
        if (view.composing)
          return;
        const changes = getTolerantConversionChanges(view.state, view.state.selection);
        if (changes.length > 0) {
          view.dispatch({ changes });
        }
      });
    }
    build(view) {
      const builder = new import_state2.RangeSetBuilder();
      const state = view.state;
      const tree = (0, import_language3.syntaxTree)(state);
      for (const { from, to } of view.visibleRanges) {
        const text = state.sliceDoc(from, to);
        CANDIDATE_REGEX.lastIndex = 0;
        let match;
        while ((match = CANDIDATE_REGEX.exec(text)) !== null) {
          if (!shouldTolerantRender(match[1]))
            continue;
          const start = from + match.index;
          const end = start + match[0].length;
          const openName = tree.cursorAt(start, 1).node.name;
          const closeName = tree.cursorAt(end - 1, 1).node.name;
          if (EXCLUDED_NODE.test(openName) || EXCLUDED_NODE.test(closeName))
            continue;
          const overlapsSelection = state.selection.ranges.some(
            (range) => range.from <= end && range.to >= start
          );
          if (overlapsSelection) {
            this.scheduleConversion(view);
            builder.add(start, start + 1, MATH_BEGIN_MARK);
            if (end - 1 > start + 1) {
              builder.add(start + 1, end - 1, MATH_CONTENT_MARK);
            }
            builder.add(end - 1, end, MATH_END_MARK);
            continue;
          }
          builder.add(start, end, import_view2.Decoration.replace({
            widget: new TolerantMathWidget(match[1])
          }));
        }
      }
      return builder.finish();
    }
  },
  {
    decorations: (instance) => instance.decorations
  }
);
var tolerantMathPostProcessor = (element) => {
  var _a;
  const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT, {
    acceptNode: (node) => {
      for (let el = node.parentElement; el && el !== element.parentElement; el = el.parentElement) {
        const tag = el.tagName;
        if (tag === "CODE" || tag === "PRE" || tag.startsWith("MJX") || el.classList.contains("math")) {
          return NodeFilter.FILTER_REJECT;
        }
      }
      return NodeFilter.FILTER_ACCEPT;
    }
  });
  const textNodes = [];
  while (walker.nextNode()) {
    textNodes.push(walker.currentNode);
  }
  let rendered = false;
  for (const textNode of textNodes) {
    const text = (_a = textNode.nodeValue) != null ? _a : "";
    CANDIDATE_REGEX.lastIndex = 0;
    let match;
    let last = 0;
    let fragment = null;
    while ((match = CANDIDATE_REGEX.exec(text)) !== null) {
      if (!shouldTolerantRender(match[1]))
        continue;
      fragment != null ? fragment : fragment = createFragment();
      fragment.append(text.slice(last, match.index));
      fragment.append(renderTolerantMath(match[1]));
      last = match.index + match[0].length;
    }
    if (fragment) {
      fragment.append(text.slice(last));
      textNode.replaceWith(fragment);
      rendered = true;
    }
  }
  if (rendered) {
    void (0, import_obsidian3.finishRenderMath)();
  }
};

// src/keyboard-switch.ts
var import_language4 = require("@codemirror/language");
var import_obsidian4 = require("obsidian");
function desktopNodeModules() {
  if (!import_obsidian4.Platform.isDesktopApp || !window.require)
    return null;
  return {
    fs: window.require("fs"),
    childProcess: window.require("child_process")
  };
}
var IM_SELECT_LOCATIONS = ["/opt/homebrew/bin/im-select", "/usr/local/bin/im-select"];
var SCAN_WINDOW = 2e3;
function findRtlLanguageAtCursor(state, commands) {
  const langCommands = commands.map((cmd) => cmd.trim().replace(/^\\/, "")).filter((cmd) => cmd === "he" || cmd === "ar");
  if (langCommands.length === 0)
    return null;
  const pos = state.selection.main.head;
  const from = Math.max(0, pos - SCAN_WINDOW);
  const text = state.sliceDoc(from, Math.min(state.doc.length, pos + SCAN_WINDOW));
  const cursor = pos - from;
  const commandRe = new RegExp(`\\\\(${langCommands.join("|")})\\{`, "g");
  let found = null;
  let match;
  while ((match = commandRe.exec(text)) !== null) {
    const argStart = match.index + match[0].length;
    if (argStart > cursor)
      break;
    let depth = 1;
    let i = argStart;
    while (i < text.length && depth > 0) {
      const ch = text[i];
      if (ch === "\\") {
        i += 2;
        continue;
      }
      if (ch === "{")
        depth++;
      else if (ch === "}")
        depth--;
      i++;
    }
    const argEnd = depth === 0 ? i - 1 : text.length;
    if (cursor >= argStart && cursor <= argEnd) {
      found = match[1];
    }
  }
  return found;
}
function isInsideMath(state, pos = state.selection.main.head) {
  const tree = (0, import_language4.syntaxTree)(state);
  const left = tree.cursorAt(pos, -1).node.name;
  const right = tree.cursorAt(pos, 1).node.name;
  if (/math/i.test(left) && !left.includes("math-end"))
    return true;
  if (/math/i.test(right) && !right.includes("math-begin"))
    return true;
  const line = state.doc.lineAt(pos);
  CANDIDATE_REGEX.lastIndex = 0;
  let match;
  while ((match = CANDIDATE_REGEX.exec(line.text)) !== null) {
    const start = line.from + match.index;
    const end = start + match[0].length;
    if (pos > start && pos < end && shouldTolerantRender(match[1]))
      return true;
  }
  return false;
}
function findKeyboardContext(state, commands) {
  const lang = findRtlLanguageAtCursor(state, commands);
  if (lang)
    return lang;
  return isInsideMath(state) ? "math" : "note";
}
var KeyboardSwitcher = class {
  constructor(plugin) {
    this.currentContext = null;
    this.targetContext = null;
    this.debounceTimeout = -1;
    this.queue = Promise.resolve();
    this.warnedMissing = false;
    this.plugin = plugin;
  }
  setContext(context) {
    if (!import_obsidian4.Platform.isDesktopApp)
      return;
    this.targetContext = context;
    window.clearTimeout(this.debounceTimeout);
    this.debounceTimeout = window.setTimeout(() => {
      const target = this.targetContext;
      this.queue = this.queue.then(() => this.transition(target)).catch(() => {
      });
    }, 150);
  }
  destroy() {
    window.clearTimeout(this.debounceTimeout);
  }
  resolveBinary() {
    const node = desktopNodeModules();
    if (!node)
      return null;
    const configured = this.plugin.settings.imSelectPath.trim();
    if (configured) {
      return node.fs.existsSync(configured) ? configured : null;
    }
    for (const location of IM_SELECT_LOCATIONS) {
      if (node.fs.existsSync(location))
        return location;
    }
    return null;
  }
  exec(bin, args) {
    return new Promise((resolve, reject) => {
      const node = desktopNodeModules();
      if (!node) {
        reject(new Error("Node.js modules are unavailable"));
        return;
      }
      node.childProcess.execFile(bin, args, { timeout: 2e3 }, (error, stdout) => {
        if (error)
          reject(error);
        else
          resolve(String(stdout).trim());
      });
    });
  }
  resolveInputSource(context) {
    const settings = this.plugin.settings;
    switch (context) {
      case "he":
        return settings.hebrewInputSource;
      case "ar":
        return settings.arabicInputSource;
      case "math":
        return settings.mathInputSource;
      case "note":
        return settings.noteInputSource;
    }
  }
  async transition(context) {
    if (context === null || context === this.currentContext)
      return;
    this.currentContext = context;
    const id = this.resolveInputSource(context).trim();
    if (!id)
      return;
    const bin = this.resolveBinary();
    if (!bin) {
      if (!this.warnedMissing) {
        this.warnedMissing = true;
        new import_obsidian4.Notice("Latex Suite Extension: im-select not found. Install it (brew install im-select) or set its path in the plugin settings to enable keyboard auto-switching.");
      }
      return;
    }
    try {
      await this.exec(bin, [id]);
    } catch (error) {
      console.warn("Latex Suite Extension: failed to switch input source", error);
    }
  }
};

// src/solve.ts
var import_view3 = require("@codemirror/view");
var import_obsidian5 = require("obsidian");
var SOLVE = "\\solve";
var createSolveListener = (plugin) => import_view3.EditorView.updateListener.of((update) => {
  if (!update.docChanged)
    return;
  if (update.transactions.some((tr) => tr.isUserEvent("undo") || tr.isUserEvent("redo")))
    return;
  const pos = update.state.selection.main.head;
  if (pos < SOLVE.length || update.state.sliceDoc(pos - SOLVE.length, pos) !== SOLVE)
    return;
  const view = update.view;
  window.setTimeout(() => trySolve(plugin, view));
});
function trySolve(plugin, view) {
  const state = view.state;
  const pos = state.selection.main.head;
  if (pos < SOLVE.length || state.sliceDoc(pos - SOLVE.length, pos) !== SOLVE)
    return;
  if (!isInsideMath(state))
    return;
  const windowStart = Math.max(0, pos - SOLVE.length - 4e3);
  let content = state.sliceDoc(windowStart, pos - SOLVE.length);
  const dollarIndex = content.lastIndexOf("$");
  if (dollarIndex >= 0)
    content = content.slice(dollarIndex + 1);
  content = content.replace(/[\r\n]+/g, " ").replace(/^\s*\{\} ?/, "");
  const insert = computeSolveInsertion(
    content,
    plugin.settings.solveSeparator,
    plugin.settings.solveAngleUnit,
    plugin.settings.solveAngleNames
  );
  if (insert === null) {
    new import_obsidian5.Notice("Latex Suite Extension: could not evaluate the last equation.");
    return;
  }
  view.dispatch({
    changes: { from: pos - SOLVE.length, to: pos, insert },
    selection: { anchor: pos - SOLVE.length + insert.length }
  });
}

// src/transaction-filter.ts
var import_state4 = require("@codemirror/state");
var import_language7 = require("@codemirror/language");

// src/snippets.ts
var import_language5 = require("@codemirror/language");
var TEXT_COMMANDS = /^(text|textrm|textbf|textit|mathrm|mathbf|mathit|mathsf|mathtt|operatorname)$/;
function sanitizeCommands(commands) {
  return commands.map((cmd) => cmd.trim().replace(/^\\/, "")).filter((cmd) => /^[A-Za-z]+$/.test(cmd));
}
function buildSnippets(rtlTextCommands) {
  const snippets = sanitizeCommands(rtlTextCommands).map((cmd) => ({
    trigger: cmd,
    replacement: `\\${cmd}{}`,
    cursorOffset: cmd.length + 2
    // right inside the braces
  }));
  snippets.push({ trigger: "sol", replacement: "\\solve", cursorOffset: 6 });
  return snippets.sort((a, b) => b.trigger.length - a.trigger.length);
}
function enclosingCommandName(state, pos) {
  const from = Math.max(0, pos - 1e3);
  const text = state.sliceDoc(from, pos);
  const commandRe = /\\([a-zA-Z]+)\s*\{/g;
  let found = null;
  let match;
  while ((match = commandRe.exec(text)) !== null) {
    let depth = 1;
    let i = match.index + match[0].length;
    while (i < text.length && depth > 0) {
      const ch = text[i];
      if (ch === "\\") {
        i += 2;
        continue;
      }
      if (ch === "{")
        depth++;
      else if (ch === "}")
        depth--;
      i++;
    }
    if (depth > 0)
      found = match[1];
  }
  return found;
}
var CODE_CONTEXT = /code|comment|frontmatter|escape|tag|hashtag/i;
function getDollarAutopair(tr) {
  const state = tr.startState;
  if (state.selection.ranges.length !== 1)
    return null;
  let single = null;
  let changeCount = 0;
  tr.changes.iterChanges((fromA2, toA2, fromB, toB, inserted2) => {
    changeCount++;
    single = { fromA: fromA2, toA: toA2, inserted: inserted2.toString() };
  });
  if (changeCount !== 1 || single === null)
    return null;
  const { fromA, toA, inserted } = single;
  if (inserted !== "$")
    return null;
  if (state.sliceDoc(Math.max(0, fromA - 1), fromA) === "\\")
    return null;
  if (CODE_CONTEXT.test((0, import_language5.syntaxTree)(state).cursorAt(fromA, 1).node.name))
    return null;
  if (toA > fromA) {
    const text = state.sliceDoc(fromA, toA);
    return {
      changes: { from: fromA, to: toA, insert: `$${text}$` },
      selection: { anchor: fromA + text.length + 2 }
    };
  }
  if (state.sliceDoc(Math.max(0, fromA - 1), fromA) === "$" && state.sliceDoc(fromA, fromA + 1) === "$" && state.sliceDoc(Math.max(0, fromA - 2), Math.max(0, fromA - 1)) !== "$" && state.sliceDoc(fromA + 1, fromA + 2) !== "$") {
    return {
      changes: { from: fromA, insert: "$$" },
      selection: { anchor: fromA + 1 }
    };
  }
  if (state.sliceDoc(fromA, fromA + 1) === "$") {
    return { selection: { anchor: fromA + 1 } };
  }
  if (state.sliceDoc(fromA, fromA + 4) === " {}$" && isInsideMath(state, fromA)) {
    return { selection: { anchor: fromA + 4 } };
  }
  if (!isInsideMath(state, fromA)) {
    return {
      changes: { from: fromA, insert: "$$" },
      selection: { anchor: fromA + 1 }
    };
  }
  return null;
}
function getSnippetExpansion(plugin, tr) {
  const state = tr.startState;
  if (state.selection.ranges.length !== 1)
    return null;
  const snippets = buildSnippets(plugin.settings.rtlTextCommands);
  const rtlCommands = sanitizeCommands(plugin.settings.rtlTextCommands);
  let result = null;
  tr.changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
    if (result !== null || inserted.length !== 1)
      return;
    const typed = inserted.toString();
    if (!/[A-Za-z]/.test(typed))
      return;
    const before = state.sliceDoc(Math.max(0, fromA - 32), fromA) + typed;
    for (const snippet of snippets) {
      if (!before.endsWith(snippet.trigger))
        continue;
      const boundary = before[before.length - snippet.trigger.length - 1];
      if (boundary !== void 0 && /[A-Za-z\\]/.test(boundary))
        continue;
      const from = fromA - (snippet.trigger.length - 1);
      if (from < 0)
        break;
      if (!isInsideMath(state, fromA))
        break;
      const enclosing = enclosingCommandName(state, fromA);
      if (enclosing && (TEXT_COMMANDS.test(enclosing) || rtlCommands.includes(enclosing)))
        break;
      result = {
        changes: { from, to: toA, insert: snippet.replacement },
        selection: { anchor: from + snippet.cursorOffset }
      };
      break;
    }
  });
  return result;
}

// src/latex-suite.ts
var import_state3 = require("@codemirror/state");
var import_language6 = require("@codemirror/language");
function handleLatexSuite(tr, plugin) {
  if (tr.docChanged && !tr.selection) {
    const changes = handleLatexSuiteBoxing(tr.startState, tr.changes);
    if (changes) {
      plugin._latexSuiteBoxing = true;
      return { changes };
    }
  } else if (!tr.docChanged && tr.selection) {
    if (plugin._latexSuiteBoxing) {
      plugin._latexSuiteBoxing = false;
      return { selection: { anchor: tr.selection.main.anchor - 3 } };
    } else {
      const selection = handleLatexSuiteTabout(tr.startState, tr.selection);
      return [tr, { selection }];
    }
  }
}
function handleLatexSuiteTabout(state, newSelection) {
  const tree = (0, import_language6.syntaxTree)(state);
  const doc = state.doc.toString();
  const newRanges = [];
  for (const range of newSelection.ranges) {
    const indexNextDollar = doc.indexOf("$", range.to);
    if (indexNextDollar >= 0) {
      const node = tree.cursorAt(indexNextDollar, 1).node;
      if (range.from === range.to && range.to === indexNextDollar && isInlineMathEnd(node, state) && state.sliceDoc(node.from - 3, node.from) === " {}") {
        newRanges.push(import_state3.EditorSelection.cursor(node.to));
        continue;
      }
    }
    newRanges.push(range);
  }
  return import_state3.EditorSelection.create(newRanges, newSelection.mainIndex);
}
function handleLatexSuiteBoxing(state, changes) {
  const tree = (0, import_language6.syntaxTree)(state);
  let changeToReplace;
  changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
    if (inserted.toString() === "\\boxed{" + state.sliceDoc(fromA, toA) + "}") {
      const nodeFrom = tree.cursorAt(fromA, -1).node;
      const nodeTo = tree.cursorAt(toA, 1).node;
      if (isInlineMathBegin(nodeFrom, state) && isInlineMathEnd(nodeTo, state)) {
        if (state.sliceDoc(fromA, fromA + 3) === "{} " && state.sliceDoc(toA - 3, toA) === " {}") {
          changeToReplace = { from: fromA, to: toA, insert: "\\boxed{" + state.sliceDoc(fromA + 3, toA - 3) + "}" };
        }
      }
    }
  });
  return changeToReplace;
}

// src/transaction-filter.ts
var import_obsidian6 = require("obsidian");
function cleanedInner(text) {
  return text.trim() || " ";
}
var makeTransactionFilter = (plugin) => {
  return import_state4.EditorState.transactionFilter.of((tr) => {
    var _a;
    if (plugin.shouldIgnore(tr.startState))
      return tr;
    const userEvent = (_a = tr.annotation(import_state4.Transaction.userEvent)) == null ? void 0 : _a.split(".")[0];
    if (userEvent === "input") {
      let hasInsertion = false;
      tr.changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
        hasInsertion || (hasInsertion = inserted.length > 0);
      });
      if (!hasInsertion)
        return tr;
      if (plugin.settings.disableOnIME) {
        const view = tr.startState.field(import_obsidian6.editorEditorField);
        if (view.composing)
          return tr;
      }
      if (plugin.settings.autoPairDollar) {
        const pairSpec = getDollarAutopair(tr);
        if (pairSpec)
          return pairSpec;
      }
      if (plugin.settings.builtinSnippets) {
        const snippetSpec = getSnippetExpansion(plugin, tr);
        if (snippetSpec)
          return snippetSpec;
      }
      const changes = getChangesForInsertion(tr.startState, tr.changes);
      const conversion = getTolerantConversionChanges(tr.startState, tr.startState.selection);
      return [tr, { changes: [changes, conversion] }];
    } else if (userEvent === "select" && tr.selection) {
      const changes = getChangesForSelection(tr.startState, tr.selection);
      const conversion = getTolerantConversionChanges(tr.startState, tr.selection);
      return [tr, { changes: [changes, conversion] }];
    } else if (userEvent === "delete") {
      const changes = getChangesForDeletion(tr.startState);
      return [tr, { changes }];
    } else if (userEvent === void 0) {
      const spec = handleLatexSuite(tr, plugin);
      if (spec)
        return spec;
    }
    return tr;
  });
};
function getChangesForDeletion(state) {
  const tree = (0, import_language7.syntaxTree)(state);
  const doc = state.doc.toString();
  const changes = [];
  for (const range of state.selection.ranges) {
    const from = range.empty ? range.from - 4 : range.from;
    const to = range.to;
    const text = state.sliceDoc(from, to);
    const index = text.lastIndexOf("$");
    if (index == -1) {
      continue;
    }
    const indexNextDollar = doc.indexOf("$", from + index + 1);
    const indexPrevDollar = doc.lastIndexOf("$", from);
    tree.iterate({
      from: indexPrevDollar,
      to: indexNextDollar >= 0 ? indexNextDollar : to,
      enter(node) {
        if (isInlineMathBegin(node, state) && state.sliceDoc(node.to, node.to + 3) == "{} ") {
          changes.push({ from: node.to, to: node.to + 3 });
        } else if (isInlineMathEnd(node, state) && state.sliceDoc(node.from - 3, node.from) == " {}") {
          changes.push({ from: node.from - 3, to: node.from });
        }
      }
    });
  }
  return changes;
}
function getChangesForInsertion(state, changes) {
  const tree = (0, import_language7.syntaxTree)(state);
  const doc = state.doc.toString();
  const changesToAdd = [];
  const beginningOfChanges = /* @__PURE__ */ new Set();
  changes.iterChangedRanges((fromA, toA, fromB, toB) => {
    beginningOfChanges.add(fromA);
  });
  for (const range of state.selection.ranges) {
    if (range.from >= 1) {
      const indexPrevDollar = doc.lastIndexOf("$", range.from - 1);
      if (indexPrevDollar >= 0) {
        const node = tree.cursorAt(indexPrevDollar, 1).node;
        if (isInlineMathBegin(node, state)) {
          if (indexPrevDollar === range.from - 1 && beginningOfChanges.has(range.from)) {
            changesToAdd.push({ from: indexPrevDollar, to: range.from, insert: "${} " });
            continue;
          }
          if (state.sliceDoc(node.to, node.to + 3) !== "{} ") {
            changesToAdd.push({ from: node.to, insert: "{} " });
          }
        } else if (isInlineMathEnd(node, state) && state.sliceDoc(node.from - 3, node.from) === " {}") {
          const openIndex = doc.lastIndexOf("${} ", node.from - 3);
          changesToAdd.push({ from: openIndex + 1, to: node.from, insert: cleanedInner(doc.slice(openIndex + 4, node.from - 3)) });
        }
      }
    }
    const indexNextDollar = doc.indexOf("$", range.to);
    if (indexNextDollar >= 0) {
      const node = tree.cursorAt(indexNextDollar, 1).node;
      if (isInlineMathEnd(node, state)) {
        if (state.sliceDoc(node.from - 3, node.from) !== " {}") {
          changesToAdd.push({ from: node.from, insert: " {}" });
        }
      } else if (isInlineMathBegin(node, state) && state.sliceDoc(node.to, node.to + 3) === "{} ") {
        const closeIndex = doc.indexOf(" {}$", node.to + 3);
        if (closeIndex >= 0) {
          changesToAdd.push({ from: node.to, to: closeIndex + 3, insert: cleanedInner(doc.slice(node.to + 3, closeIndex)) });
        }
      }
    }
  }
  return changesToAdd;
}
function getChangesForSelection(state, newSelection) {
  const tree = (0, import_language7.syntaxTree)(state);
  const doc = state.doc.toString();
  const changes = [];
  for (let i = 0; i < newSelection.ranges.length; i++) {
    const range = newSelection.ranges[i];
    const indexNextDollar = doc.indexOf("$", range.to);
    const indexPrevDollar = doc.lastIndexOf("$", range.from - 1);
    if (indexPrevDollar >= 0) {
      const node = tree.cursorAt(indexPrevDollar, 1).node;
      if (isInlineMathEnd(node, state) && state.sliceDoc(node.from - 3, node.from) === " {}") {
        const openIndex = doc.lastIndexOf("${} ", node.from - 3);
        changes.push({ from: openIndex + 1, to: node.from, insert: cleanedInner(doc.slice(openIndex + 4, node.from - 3)) });
      }
    }
    if (indexNextDollar >= 0) {
      const node = tree.cursorAt(indexNextDollar, 1).node;
      if (isInlineMathBegin(node, state) && state.sliceDoc(node.to, node.to + 3) === "{} ") {
        const closeIndex = doc.indexOf(" {}$", node.to + 3);
        if (closeIndex >= 0) {
          changes.push({ from: node.to, to: closeIndex + 3, insert: cleanedInner(doc.slice(node.to + 3, closeIndex)) });
        }
      }
    }
  }
  return changes;
}

// src/main.ts
var LatexSuiteExtension = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    /**
     * a view plugin that provides
     * - decorations to hide braces adjacent to "$"s
     * - & atomic ranges to treat each of "${} " and " {}$" as one character
     */
    this.viewPlugin = [];
    /**
     * Indicates whether the previous transaction was the first of the two transactions
     * (1. text replacement & 2. cursor position change) that Latex Suite's "box current equation"
     * command produces or not. See the comment in the makeTransactionFilter() method for details.
     */
    this._latexSuiteBoxing = false;
  }
  async onload() {
    await this.loadSettings();
    await this.saveSettings();
    this.addSettingTab(new LatexSuiteExtensionSettingTab(this.app, this));
    await this.refreshMathJax();
    this.patchInlineDisplaystyle();
    this.applyRtlFonts();
    this.registerEditorExtension(this.viewPlugin);
    this.remakeViewPlugin();
    this.registerEditorExtension(makeTransactionFilter(this));
    this.registerEditorExtension(tolerantMathViewPlugin);
    this.registerMarkdownPostProcessor(tolerantMathPostProcessor);
    this.registerEditorExtension(createSolveListener(this));
    if (import_obsidian7.Platform.isDesktopApp) {
      this.keyboardSwitcher = new KeyboardSwitcher(this);
      this.registerEditorExtension(import_view4.EditorView.updateListener.of((update) => {
        if (!this.settings.autoSwitchKeyboard || !this.keyboardSwitcher)
          return;
        if (!update.selectionSet && !update.docChanged)
          return;
        if (!update.view.hasFocus)
          return;
        this.keyboardSwitcher.setContext(
          findKeyboardContext(update.state, this.settings.rtlTextCommands)
        );
      }));
      this.addCommand({
        id: "toggle-keyboard-auto-switch",
        name: "Toggle keyboard auto-switching",
        callback: async () => {
          this.settings.autoSwitchKeyboard = !this.settings.autoSwitchKeyboard;
          await this.saveSettings();
          new import_obsidian7.Notice(`Keyboard auto-switching ${this.settings.autoSwitchKeyboard ? "enabled" : "disabled"}`);
        }
      });
    }
  }
  onunload() {
    var _a, _b;
    (_a = this.mathjaxPatcher) == null ? void 0 : _a.destroy();
    this.mathjaxPatcher = void 0;
    document.body.removeClass("lse-rtl-fonts");
    document.body.style.removeProperty("--lse-rtl-fonts");
    (_b = this.keyboardSwitcher) == null ? void 0 : _b.destroy();
    this.keyboardSwitcher = void 0;
    if (this.origTex2chtml && window.MathJax) {
      window.MathJax.tex2chtml = this.origTex2chtml;
      this.origTex2chtml = void 0;
    }
  }
  /**
   * Wraps MathJax's tex2chtml so inline math (display: false) is rendered
   * with a leading \displaystyle. Reading the setting at render time means
   * the toggle needs no re-patching; math already on screen re-renders when
   * its note is reopened.
   */
  patchInlineDisplaystyle() {
    const mathJax = window.MathJax;
    if (!(mathJax == null ? void 0 : mathJax.tex2chtml) || this.origTex2chtml)
      return;
    const original = mathJax.tex2chtml.bind(mathJax);
    this.origTex2chtml = original;
    mathJax.tex2chtml = (source, options) => {
      if (this.settings.inlineDisplaystyle && (options == null ? void 0 : options.display) === false && !source.includes("\\displaystyle")) {
        source = "\\displaystyle " + source;
      }
      return original(source, options);
    };
  }
  /**
   * The font rule itself lives statically in styles.css; this only toggles
   * the body class gating it and fills in the font stack via a CSS variable.
   */
  applyRtlFonts() {
    const stack = buildRtlFontStack(this.settings.hebrewFont, this.settings.arabicFont);
    if (stack) {
      document.body.addClass("lse-rtl-fonts");
      document.body.style.setProperty("--lse-rtl-fonts", stack);
    } else {
      document.body.removeClass("lse-rtl-fonts");
      document.body.style.removeProperty("--lse-rtl-fonts");
    }
  }
  async loadSettings() {
    const data = await this.loadData();
    const stored = data != null ? data : {};
    this.settings = Object.assign({}, DEFAULT_SETTINGS, stored);
    this.settings.rtlTextCommands = Array.isArray(stored.rtlTextCommands) ? stored.rtlTextCommands : [...DEFAULT_SETTINGS.rtlTextCommands];
    this.settings.solveAngleNames = Array.isArray(stored.solveAngleNames) ? stored.solveAngleNames : [...DEFAULT_SETTINGS.solveAngleNames];
    if (this.settings.solveSeparator === "\\quad \\xrightarrow{} \\quad") {
      this.settings.solveSeparator = DEFAULT_SETTINGS.solveSeparator;
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async refreshMathJax() {
    var _a;
    (_a = this.mathjaxPatcher) == null ? void 0 : _a.destroy();
    this.mathjaxPatcher = new MathJaxBidiCommandPatcher(this.settings.rtlTextCommands);
    await this.mathjaxPatcher.init();
  }
  shouldIgnore(state) {
    return this.settings.disableInTable && selectionSatisfies(
      state,
      (node) => node.name.includes("HyperMD-table") || node.name.includes("hmd-table")
    );
  }
  remakeViewPlugin() {
    this.viewPlugin.length = 0;
    this.viewPlugin.push(createViewPlugin(this));
    this.app.workspace.updateOptions();
  }
};

/* nosourcemap */